---
abstract: 'Subversion repository web frontend'
author:
  - 'Dean Hamstead <dean@fragfest.com.au>'
build_requires:
  Cwd: 0
  File::Copy: 0
  File::Find: 0
  File::Path: 0
  Test::More: 0
  Test::WWW::Mechanize: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300025, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SVN-Web
recommends:
  Cache::Cache: 0
  Template::Plugin::Clickable: 0
  Template::Plugin::Clickable::Email: 0
  Template::Plugin::Subst: 0
  Test::Benchmark: 0
  Test::HTML::Tidy: 0
  XML::RSS::Parser: 0
requires:
  Alien::SVN: 0
  Carp: 0
  Encode: 0
  Exception::Class: 1.22
  File::Basename: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  FindBin: 0
  IO::File: 0
  List::Util: 0
  Locale::Maketext: 0
  Locale::Maketext::Lexicon: 0
  Number::Format: 0
  POSIX: 0
  Plack: 0
  Template: 0
  Template::Plugin::Number::Format: 0
  Time::Zone: 0
  URI::Escape: 0
  YAML: 0
  base: 0
  perl: 5.00404
  strict: 0
  vars: 0
  warnings: 0
version: 0.63
