name: SVN-Web
version: 0.37
abstract: Subversion repository web frontend
author: Chia-liang Kao <clkao@clkao.org>
license: perl
distribution_type: module
requires:
  SVN::Core: 1.0.4
  Template: 0
  YAML: 0
  XML::RSS: 0
  Text::Diff: 0
  Locale::Maketext::Simple: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.330
