# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SVN-Web
version:      0.35
version_from: lib/SVN/Web.pm
installdirs:  site
requires:
    SVN::Core:                     0.29.0
    Template:                      0
    Text::Diff:                    0
    XML::RSS:                      0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
